site_name: Geoapify Geocoder Autocomplete
site_url: https://geoapify.github.io/geocoder-autocomplete/

theme:
  name: material
  logo: assets/geoapify-white-logo-only.png
  favicon: assets/favicon.ico
  features:
    - content.code.copy
    - navigation.expand

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search

nav:
  - Home: index.md
  - Quick Start: quick-start.md
  - API Reference:
      - GeocoderAutocomplete: api-reference/geocoder-autocomplete.md
      - GeocoderAutocompleteOptions: api-reference/geocoder-autocomplete-options.md
  - Styling: styling.md
  - Interactive Demos: live-demos.md

repo_url: https://github.com/geoapify/geocoder-autocomplete
repo_name: GitHub

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/geoapify
